name: Daily Integration Tests
on:
  schedule:
    - cron: 0 10 * * *
  workflow_dispatch:

jobs:
  Check-For-Changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.commits.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - name: Check for commits
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_ENV
      - id: commits
        run: echo "changes=$NEW_COMMIT_COUNT" >> "$GITHUB_OUTPUT"

  Integration-Test:
    name: ${{ matrix.version }} - Integration Tests
    runs-on: macos-latest
    needs: Check-For-Changes
    if: ${{ needs.Check-For-Changes.outputs.changes > 0 }}
    strategy:
      fail-fast: false
      matrix:
        version: [ 1.56.0, latest, insider ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies and requirements
        run: |
          npm ci
          npm i titanium alloy -g
          ti sdk install latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Integration Tests
        run: npm run test:integration
        env:
          CODE_STREAM: ${{ matrix.version }}
